# Generated by Django 5.1 on 2026-01-16 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Match_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html', models.CharField(max_length=10000000)),
                ('user', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'HTML Doc for Automated pdf and word report',
                'verbose_name_plural': 'HTML Doc for Automated pdf and word report',
            },
        ),
        migrations.CreateModel(
            name='pay_load_string',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payLoadString', models.JSONField()),
                ('user', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Automated JSON triger field for Click up and Front End (One API end point)',
                'verbose_name_plural': 'Automated JSON triger field for Click up and Front End (One API end point)',
            },
        ),
    ]
