# Generated by Django 5.1 on 2025-06-27 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0002_pay_load_string'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pay_load_string',
            name='payLoadString',
            field=models.JSONField(),
        ),
    ]
