# Generated by Django 5.1 on 2025-10-08 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0003_alter_pay_load_string_payloadstring'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match_data',
            options={'verbose_name': 'HTML Doc for Automated pdf and word report', 'verbose_name_plural': 'HTML Doc for Automated pdf and word report'},
        ),
        migrations.AlterModelOptions(
            name='pay_load_string',
            options={'verbose_name': 'Automated JSON triger field for Click up and Front End (One API end point)', 'verbose_name_plural': 'Automated JSON triger field for Click up and Front End (One API end point)'},
        ),
    ]
