# Generated by Django 5.1 on 2026-04-29 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='capitalTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=300)),
            ],
            options={
                'verbose_name': 'Algorithm name',
                'verbose_name_plural': 'Algorithm names',
            },
        ),
        migrations.CreateModel(
            name='CapitalType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matrix_weights', models.JSONField(blank=True, default=list, null=True)),
                ('counterlist', models.JSONField(blank=True, default=list, null=True)),
                ('counter', models.IntegerField(default=0, null=True)),
                ('status', models.BooleanField(default=0, null=True)),
                ('namec', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Algorithm.capitaltypes')),
            ],
        ),
    ]
