# Generated by Django 5.1 on 2026-04-29 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='accent_color',
            field=models.CharField(blank=True, default='', max_length=9),
        ),
        migrations.AddField(
            model_name='client',
            name='contact_phone',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='client',
            name='display_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='client',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='tenant_branding/'),
        ),
        migrations.AddField(
            model_name='client',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='tenant_branding/'),
        ),
        migrations.AddField(
            model_name='client',
            name='primary_color',
            field=models.CharField(blank=True, default='', help_text='Hex color, e.g. #1f6feb', max_length=9),
        ),
        migrations.AddField(
            model_name='client',
            name='signatory_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='client',
            name='signature_image',
            field=models.ImageField(blank=True, null=True, upload_to='tenant_branding/'),
        ),
        migrations.AddField(
            model_name='client',
            name='support_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
