# Generated by Django 5.1 on 2026-05-14 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_client_accent_color_client_contact_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='address',
            field=models.TextField(blank=True, default='', help_text='Multi-line postal address used in the letter footer.'),
        ),
        migrations.AddField(
            model_name='client',
            name='signatory_title',
            field=models.CharField(blank=True, default='', help_text='Job title shown under the signatory name on generated letters (e.g. "Chief Revenue Officer").', max_length=120),
        ),
    ]
