# Generated by Django 5.1 on 2026-05-18 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_client_address_client_signatory_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='current_period_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='stripe_customer_id',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='client',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='client',
            name='subscription_plan_slug',
            field=models.CharField(blank=True, default='', help_text='Slug of the subscriptions.Plan currently in effect (e.g. "monthly", "yearly").', max_length=64),
        ),
        migrations.AddField(
            model_name='client',
            name='subscription_status',
            field=models.CharField(blank=True, default='', help_text='Latest Stripe status: trialing / active / past_due / canceled / incomplete / incomplete_expired / unpaid.', max_length=32),
        ),
        migrations.AddField(
            model_name='client',
            name='trial_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
