# Generated by Django 5.1 on 2025-08-15 09:12

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=200)),
                ('task_max_hour', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(32)])),
                ('task_type', models.CharField(choices=[('FINFIRE Staff Review & Scope of Work', 'FINFIREStaff Review & Scope of Work'), ('Intermediary Services Scope of Work', 'Intermediary Services Scope of Work')], max_length=200)),
                ('task_precedence', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['task_precedence'],
            },
        ),
        migrations.CreateModel(
            name='rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='truth_in_capital.task')),
            ],
            options={
                'verbose_name': 'rating',
            },
        ),
        migrations.CreateModel(
            name='TruthCapitalType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capital_type', models.CharField(choices=[('Accelerator', 'Accelerator'), ('Bonds', 'Bonds'), ('Bootstrapped', 'Bootstrapped'), ('Commercial Banking', 'Commercial Banking'), ('Cryptocurrency', 'Cryptocurrency'), ('Factoring', 'Factoring'), ('Grants', 'Grants'), ('Hedge Funds', 'Hedge Funds'), ('Incubator', 'Incubator'), ('Investment Banking', 'Investment Banking'), ('Private Debt', 'Private Debt'), ('Private Equity Securities', 'Private Equity Securities'), ('Royalty Financing', 'Royalty Financing'), ('Small Business Administration (SBA)', 'Small Business Administration (SBA)'), ('Third Party Corporate Credit', 'Third Party Corporate Credit'), ('Tokenization', 'Tokenization'), ('Venture Capital', 'Venture Capital')], max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Capital Type',
                'verbose_name_plural': 'Capital Types',
                'unique_together': {('user', 'capital_type')},
            },
        ),
        migrations.CreateModel(
            name='time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('duration_capital_weeks', models.DurationField()),
                ('capital_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='time', to='truth_in_capital.truthcapitaltype')),
            ],
            options={
                'verbose_name': 'timing',
            },
        ),
        migrations.AddField(
            model_name='task',
            name='capital_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='truth_in_capital.truthcapitaltype'),
        ),
    ]
