# Generated by Django 5.1 on 2025-08-20 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('truth_in_capital', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='time',
            name='duration_capital_weeks',
        ),
    ]
