# Generated by Django 5.1 on 2025-10-08 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('truth_in_capital', '0002_remove_time_duration_capital_weeks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={'verbose_name': 'D. rating', 'verbose_name_plural': 'D. ratings'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['task_precedence'], 'verbose_name': 'B. Task', 'verbose_name_plural': 'B. Task'},
        ),
        migrations.AlterModelOptions(
            name='time',
            options={'verbose_name': 'C. Time', 'verbose_name_plural': 'C. Time'},
        ),
        migrations.AlterModelOptions(
            name='truthcapitaltype',
            options={'verbose_name': 'A. Capital Type', 'verbose_name_plural': 'A. Capital Types'},
        ),
    ]
