# Generated by Django 5.1 on 2025-02-13 06:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VQuestion1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=200)),
                ('Last_Name', models.CharField(max_length=200)),
                ('Company_Name', models.CharField(max_length=200)),
                ('Primary_Phone', models.CharField(max_length=200)),
                ('Secondary_Phone', models.CharField(max_length=200)),
                ('Alternate_Phone', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=200)),
                ('Adress', models.CharField(max_length=200)),
                ('City', models.CharField(max_length=200)),
                ('State', models.CharField(choices=[('Alabama', 'Alabama'), ('Alaska', 'Alaska'), ('Arizona', 'Arizona'), ('Arkansas', 'Arkansas'), ('California', 'California'), ('Colorado', 'Colorado'), ('Connecticut', 'Connecticut'), ('Delaware', 'Delaware'), ('Florida', 'Florida'), ('Georgia', 'Georgia'), ('Hawaii', 'Hawaii'), ('Idaho', 'Idaho'), ('Illinois', 'Illinois'), ('Indiana', 'Indiana'), ('Iowa', 'Iowa'), ('Kansas', 'Kansas'), ('Kentucky', 'Kentucky'), ('Louisiana', 'Louisiana'), ('Maine', 'Maine'), ('Maryland', 'Maryland'), ('Massachusetts', 'Massachusetts'), ('Michigan', 'Michigan'), ('Minnesota', 'Minnesota'), ('Mississippi', 'Mississippi'), ('Missouri', 'Missouri'), ('Montana', 'Montana'), ('Nebraska', 'Nebraska'), ('Nevada', 'Nevada'), ('New Hampshire', 'New Hampshire'), ('New Jersey', 'New Jersey'), ('New Mexico', 'New Mexico'), ('New York', 'New York'), ('North Carolina', 'North Carolina'), ('North Dakota', 'North Dakota'), ('Ohio', 'Ohio'), ('Oklahoma', 'Oklahoma'), ('Oregon', 'Oregon'), ('Pennsylvania', 'Pennsylvania'), ('Rhode Island', 'Rhode Island'), ('South Carolina', 'South Carolina'), ('South Dakota', 'South Dakota'), ('Tennessee', 'Tennessee'), ('Texas', 'Texas'), ('Utah', 'Utah'), ('Vermont', 'Vermont'), ('Virginia', 'Virginia'), ('Washington', 'Washington'), ('West Virginia', 'West Virginia'), ('Wisconsin', 'Wisconsin'), ('Wyoming', 'Wyoming')], max_length=200)),
                ('Zip_Code', models.CharField(max_length=200)),
                ('CM_Type', models.CharField(choices=[('66- Private Equity Securities - Regulation CF Tittle III', '66- Private Equity Securities - Regulation CF Tittle III'), ('65- Private Equity Securities - Regulation A', '65- Private Equity Securities - Regulation A'), ('1- Private Equity', '1- Private Equity'), ('77- Small Business Administration (SBA) - SBA 504B', '77- Small Business Administration (SBA) - SBA 504B'), ('21- Commercial Banking - Line of Credit', '21- Commercial Banking - Line of Credit'), ('Regulation D 506B', 'Regulation D 506B'), ('Exempt Securities', 'Exempt Securities'), ('75- Private Equity Securities - Simple Agreement Future Equity', '75- Private Equity Securities - Simple Agreement Future Equity'), ('Business Accelerator', 'Business Accelerator'), ('Business Incubator', 'Business Incubator'), ('79- Small Business Administration (SBA) - SBA Micro Lender', '79- Small Business Administration (SBA) - SBA Micro Lender')], max_length=200)),
                ('Capital_Amount', models.CharField(choices=[('Less Than $25,000', 'Less Than $25,000'), ('$26,000 to $99,000', '$26,000 to $99,000'), ('$250,000 to $499,999', '$250,000 to $499,999'), ('$500,000 to $999,999', '$500,000 to $999,999'), ('$1,000,000 to $1,349,999', '$1,000,000 to $1,349,999'), ('$1,350,000 to $1,999,999', '$1,350,000 to $1,999,999'), ('$2,000,000 to $4,999,999', '$2,000,000 to $4,999,999'), ('$5,000,000 to $9,999,999', '$5,000,000 to $9,999,999'), ('$10,000,000 to $19,999,999', '$10,000,000 to $19,999,999'), ('More Than $20 Million', 'More Than $20 Million'), ("Unsure/Don't Know/TBD", "Unsure/Don't Know/TBD")], max_length=200, null=True)),
                ('Dry_Powder', models.CharField(choices=[('Less Than $25,000', 'Less Than $25,000'), ('$26,000 to $99,000', '$26,000 to $99,000'), ('$250,000 to $499,999', '$250,000 to $499,999'), ('$500,000 to $999,999', '$500,000 to $999,999'), ('$1,000,000 to $1,349,999', '$1,000,000 to $1,349,999'), ('$1,350,000 to $1,999,999', '$1,350,000 to $1,999,999'), ('$2,000,000 to $4,999,999', '$2,000,000 to $4,999,999'), ('$5,000,000 to $9,999,999', '$5,000,000 to $9,999,999'), ('$10,000,000 to $19,999,999', '$10,000,000 to $19,999,999'), ('More Than $20 Million', 'More Than $20 Million'), ("Unsure/Don't Know/TBD", "Unsure/Don't Know/TBD")], default=None, max_length=200, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Capital Markets Database',
                'verbose_name_plural': 'Capital Markets Database',
            },
        ),
    ]
