# Generated by Django 5.1 on 2026-01-16 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=200)),
                ('Middle_Name', models.CharField(blank=True, max_length=200)),
                ('Last_Name', models.CharField(max_length=200)),
                ('Affiliation', models.JSONField(blank=True, default=list, help_text='Leave this blank as it may cause error.')),
                ('User_Email', models.EmailField(max_length=254)),
                ('Company_Website', models.CharField(blank=True, max_length=200)),
                ('Business_Adress', models.CharField(blank=True, max_length=200)),
                ('Business_Phone', models.CharField(blank=True, max_length=200)),
                ('Mobile_Phone', models.CharField(blank=True, max_length=200)),
                ('Special_Programs', models.JSONField(blank=True, default=dict, help_text='Leave this blank as it may cause error.')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'A. Contact Information (UserDetails)',
                'verbose_name_plural': 'A. Contact Information (UserDetails)',
            },
        ),
        migrations.CreateModel(
            name='UserDetail2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Account_Type', models.CharField(choices=[('Capital Market', 'Capital Market'), ('Enterprise/Business', 'Enterprise/Business'), ('Intermediary', 'Intermediary')], max_length=200)),
                ('Primary_Purpose', models.JSONField(blank=True, choices=[('Consultant and/or Intermediary Seeking Leads & Providing Advice', 'Consultant and/or Intermediary Seeking Leads & Providing Advice'), ('Cost to Package the Right Capital Type to the Situation', 'Cost to Package the Right Capital Type to the Situation'), ('Education - Learn the Capital Markets & Capital Types Available', 'Education - Learn the Capital Markets & Capital Types Available'), ('I Don’t Know - TBD', 'I Don’t Know - TBD'), ('Identify Documents Required for the Most Probable Capital Type', 'Identify Documents Required for the Most Probable Capital Type'), ('Information - Match the Right Capital to the Situation', 'Information - Match the Right Capital to the Situation'), ('Introductions to Capital Sources Currently Funding', 'Introductions to Capital Sources Currently Funding'), ('Introductions to Qualified Companies Seeking Capital', 'Introductions to Qualified Companies Seeking Capital'), ('Timeline to Capital', 'Timeline to Capital')], default=dict, help_text='Leave this blank as it may cause error.')),
                ('Billing_Option', models.CharField(blank=True, choices=[('Silver', 'Silver'), ('Gold', 'Gold'), ('Platinum', 'Platinum')], max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'B. Account Setup (UserDetails2)',
                'verbose_name_plural': 'B. Account Setup (UserDetails2)',
            },
        ),
    ]
