# Generated by Django 5.1 on 2025-04-06 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='Business_Phone',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='Mobile_Phone',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
