# Generated by Django 5.1 on 2025-10-08 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_alter_userdetail_business_phone_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdetail',
            options={'verbose_name': 'A. Contact Information (UserDetails)', 'verbose_name_plural': 'A. Contact Information (UserDetails)'},
        ),
        migrations.AlterModelOptions(
            name='userdetail2',
            options={'verbose_name': 'B. Account Setup (UserDetails2)', 'verbose_name_plural': 'B. Account Setup (UserDetails2)'},
        ),
    ]
