# Generated by Django 5.1 on 2026-01-16 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IQuestions1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=200)),
                ('Last_Name', models.CharField(max_length=200)),
                ('Company_Name', models.CharField(max_length=200)),
                ('Primary_Phone', models.CharField(max_length=200)),
                ('Secondary_Phone', models.CharField(max_length=200)),
                ('Alternate_Phone', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=200)),
                ('Adress', models.CharField(max_length=200)),
                ('City', models.CharField(max_length=200)),
                ('State', models.CharField(choices=[('Alabama', 'Alabama'), ('Alaska', 'Alaska'), ('Arizona', 'Arizona'), ('Arkansas', 'Arkansas'), ('California', 'California'), ('Colorado', 'Colorado'), ('Connecticut', 'Connecticut'), ('Delaware', 'Delaware'), ('Florida', 'Florida'), ('Georgia', 'Georgia'), ('Hawaii', 'Hawaii'), ('Idaho', 'Idaho'), ('Illinois', 'Illinois'), ('Indiana', 'Indiana'), ('Iowa', 'Iowa'), ('Kansas', 'Kansas'), ('Kentucky', 'Kentucky'), ('Louisiana', 'Louisiana'), ('Maine', 'Maine'), ('Maryland', 'Maryland'), ('Massachusetts', 'Massachusetts'), ('Michigan', 'Michigan'), ('Minnesota', 'Minnesota'), ('Mississippi', 'Mississippi'), ('Missouri', 'Missouri'), ('Montana', 'Montana'), ('Nebraska', 'Nebraska'), ('Nevada', 'Nevada'), ('New Hampshire', 'New Hampshire'), ('New Jersey', 'New Jersey'), ('New Mexico', 'New Mexico'), ('New York', 'New York'), ('North Carolina', 'North Carolina'), ('North Dakota', 'North Dakota'), ('Ohio', 'Ohio'), ('Oklahoma', 'Oklahoma'), ('Oregon', 'Oregon'), ('Pennsylvania', 'Pennsylvania'), ('Rhode Island', 'Rhode Island'), ('South Carolina', 'South Carolina'), ('South Dakota', 'South Dakota'), ('Tennessee', 'Tennessee'), ('Texas', 'Texas'), ('Utah', 'Utah'), ('Vermont', 'Vermont'), ('Virginia', 'Virginia'), ('Washington', 'Washington'), ('West Virginia', 'West Virginia'), ('Wisconsin', 'Wisconsin'), ('Wyoming', 'Wyoming')], max_length=200)),
                ('Zip_Code', models.CharField(max_length=200)),
                ('I_Type', models.CharField(choices=[('Technical_Writer', 'Technical_Writer'), ('Content_Creator', 'Content_Creator'), ('Business_Consultant', 'Business_Consultant'), ('Marketing_Analyst', 'Marketing_Analyst'), ('Business_Plan_Writer', 'Business_Plan_Writer'), ('Business_Attorney', 'Business_Attorney'), ('Exempt Securities', 'Exempt Securities'), ('Researcher', 'Researcher'), ('Subject_Matter_Expert', 'Subject_Matter_Expert'), ('Business_Analyst', 'Business_Analyst'), ('Data_Entry', 'Data_Entry'), ('Financial_Analyst', 'Financial_Analyst'), ('Accountant', 'Accountant'), ('CPA', 'CPA'), ('Financial Modeler', 'Financial Modeler'), ('Valuation_Analyst', 'Valuation_Analyst'), ('Banker', 'Banker'), ('Web_Developer', 'Web_Developer'), ('Marketing_Consultant', 'Marketing_Consultant'), ('Transfer_Agency', 'Transfer_Agency'), ('Graphic_Designer', 'Graphic_Designer'), ('Hr_Due_Diligence', 'Hr_Due_Diligence'), ('Management_Consultant', 'Management_Consultant'), ('Hr_Consultant', 'Hr_Consultant'), ('Culture_Subject_Matter_Expert', 'Culture_Subject_Matter_Expert'), ('Broker_Agency', 'Broker_Agency'), ('Platform', 'Platform'), ('Securities_Attorney', 'Securities_Attorney'), ('Paralegal', 'Paralegal'), ('Intelectual_Property_Attorney', 'Intelectual_Property_Attorney'), ('Legal_Assistant', 'Legal_Assistant'), ('Risk_Analyst', 'Risk_Analyst'), ('Underwritter', 'Underwritter')], max_length=200)),
                ('Prefered_CM', models.JSONField()),
                ('Specialized_Industry', models.JSONField()),
                ('Regions_Served', models.JSONField()),
                ('Selected_Options', models.JSONField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IQuestions2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(choices=[('Hourly', 'Hourly'), ('Fixed Price', 'Fixed Price'), ('Commission', 'Commission'), ('Royalty', 'Royalty'), ('By the Project', 'By the Project'), ('Success Fees', 'Success Fees'), ('Others', 'Others')], max_length=50)),
                ('Explanation', models.TextField(blank=True, max_length=1000, null=True)),
                ('Rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
