# Generated by Django 5.1 on 2025-08-01 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise_questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equestions',
            name='Selected_Option',
            field=models.CharField(choices=[('Minimum $0 - Maximum $499', 'Minimum $0 - Maximum $499'), ('Minimum $500 - Maximum $999', 'Minimum $500 - Maximum $999'), ('Minimum $1000 - Maximum $2499', 'Minimum $1000 - Maximum $2499'), ('Minimum $2500 - Maximum $4999', 'Minimum $2500 - Maximum $4999'), ('Minimum $5000 - Maximum $9999', 'Minimum $5000 - Maximum $9999'), ('Minimum $10000 - Maximum $24999', 'Minimum $10000 - Maximum $24999'), ('Minimum $25000 - Maximum $49999', 'Minimum $25000 - Maximum $49999'), ('More than $50000+', 'More than $50000+')], help_text='Select same option as chosen above.', max_length=200),
        ),
        migrations.AlterField(
            model_name='equestions',
            name='Selected_Option2',
            field=models.CharField(choices=[('1 Day to 1 Week', '1 Day to 1 Week'), ('1 Week to 2 Week', '1 Week to 2 Week'), ('2 Weeks to 4 Weeks', '2 Weeks to 4 Weeks'), ('1 Month to 2 Months', '1 Month to 2 Months'), ('2 Months to 3 Months', '2 Months to 3 Months'), ('3 Months to 6 Months', '3 Months to 6 Months'), ('6 Months to 12 Months', '6 Months to 12 Months'), ('More than 1 year', 'More than 1 year')], help_text='Select same option as chosen above.', max_length=200),
        ),
    ]
