# Generated by Django 5.1 on 2026-05-14 08:23

from django.db import migrations, models


def fix_entertainment_typo(apps, schema_editor):
    """Migrate any existing rows that hold the old 'Entertainmen' typo
    value to the corrected 'Entertainment' so they still validate under
    the new choices."""
    EQuestions14 = apps.get_model('entreprise_questions', 'EQuestions14')
    EQuestions14.objects.filter(Industry_Type='Entertainmen').update(
        Industry_Type='Entertainment',
    )


def revert_entertainment_typo(apps, schema_editor):
    """Reverse migration: put rows back to the typo'd value."""
    EQuestions14 = apps.get_model('entreprise_questions', 'EQuestions14')
    EQuestions14.objects.filter(Industry_Type='Entertainment').update(
        Industry_Type='Entertainmen',
    )


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise_questions', '0001_initial'),
    ]

    operations = [
        # Update existing rows BEFORE tightening the choices, otherwise the
        # data migration would briefly run with the new choices list and an
        # invalid 'Entertainmen' value sitting in the column.
        migrations.RunPython(
            fix_entertainment_typo,
            reverse_code=revert_entertainment_typo,
        ),
        migrations.AlterField(
            model_name='equestions14',
            name='Industry_Type',
            field=models.CharField(choices=[('Administration', 'Administration'), ('Agriculture', 'Agriculture'), ('Arts', 'Arts'), ('Energy/Utilities', 'Energy/Utilities'), ('Entertainment', 'Entertainment'), ('Finance', 'Finance'), ('High tech', 'High tech'), ('Hospitality, F & B', 'Hospitality, F & B'), ('Info Services', 'Info Services'), ('Manufacturing', 'Manufacturing'), ('Mining', 'Mining'), ('Professional Insurance/Mgmt', 'Professional Insurance/Mgmt'), ('Real State', 'Real State'), ('Science - Health - Medicine', 'Science - Health - Medicine'), ('Sector/Sub-Sector', 'Sector/Sub-Sector'), ('Trades - Construction', 'Trades - Construction'), ('Transportation & Logistics', 'Transportation & Logistics'), ('Waste Management', 'Waste Management'), ('Wholesale & Retail', 'Wholesale & Retail'), ('Other', 'Other')], help_text='Select Your Industry Type', max_length=200),
        ),
    ]
