# Generated by Django 5.1 on 2025-08-01 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise_questions', '0002_alter_equestions_selected_option_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equestions',
            name='Selected_Option',
            field=models.CharField(choices=[('Minimum $0 - Maximum $499', 'Minimum $0 - Maximum $499'), ('$500 - $999', '$500 - $999'), ('$1000 - $2499', '$1000 - $2499'), ('$2500 - $4999', '$2500 - $4999'), ('$5000 - $9999', '$5000 - $9999'), ('$10000 - $24999', '$10000 - $24999'), ('$25000 - $49999', '$25000 - $49999'), ('$50000+', '$50000+')], help_text='Select same option as chosen above.', max_length=200),
        ),
        migrations.AlterField(
            model_name='equestions',
            name='Selected_Option2',
            field=models.CharField(choices=[('1 Day to 1 Week', '1 Day to 1 Week'), ('1 Week to 2 Weeks', '1 Week to 2 Weeks'), ('2 Weeks to 4 Weeks', '2 Weeks to 4 Weeks'), ('1 Month to 2 Months', '1 Month to 2 Months'), ('2 Months to 3 Months', '2 Months to 3 Months'), ('3 Months to 6 Months', '3 Months to 6 Months'), ('6 Months to 12 Months', '6 Months to 12 Months'), ('More than 1 year', 'More than 1 year')], help_text='Select same option as chosen above.', max_length=200),
        ),
    ]
