# Generated by Django 5.1 on 2025-09-04 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise_questions', '0004_pre_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='referal_response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_source', models.CharField(choices=[('friend', 'A Friend / Colleague'), ('advisor', 'Financial Advisor / Consultant'), ('social', 'Social Media'), ('search', 'Online Search'), ('news', 'News / Article / Blog'), ('event', 'Event / Webinar'), ('other', 'Other')], default=None, max_length=20, null=True, verbose_name='How did you hear about us?')),
                ('referrer_name', models.CharField(default=None, max_length=255, null=True, verbose_name="Referrer's Name (if any)")),
                ('referral_other', models.CharField(default=None, max_length=255, null=True, verbose_name='Other (please specify)')),
            ],
        ),
        migrations.AlterField(
            model_name='pre_rating',
            name='preratings',
            field=models.JSONField(default=dict),
        ),
    ]
