# Generated by Django 5.1 on 2025-09-25 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise_questions', '0006_referal_response_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referal_response',
            name='referral_other',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Other (please specify)'),
        ),
    ]
