# Generated by Django 5.1 on 2025-10-08 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise_questions', '0007_alter_referal_response_referral_other'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentsprepared',
            options={'verbose_name': 'I. Documents Prepared (Equestions 12)', 'verbose_name_plural': 'I. Documents Prepared (Equestions 12)'},
        ),
        migrations.AlterModelOptions(
            name='equestions',
            options={'verbose_name': 'J. Cost & Timming (Equestions 10 & 11)', 'verbose_name_plural': 'Cost & Timming (Equestions 10 & 11)'},
        ),
        migrations.AlterModelOptions(
            name='equestions1',
            options={'verbose_name': 'A. Stage (Equestions1)', 'verbose_name_plural': 'A. Stage (Equestions1)'},
        ),
        migrations.AlterModelOptions(
            name='equestions2',
            options={'verbose_name': 'B. Entity, (Equestions2)', 'verbose_name_plural': 'B. Entity, (Equestions2)'},
        ),
        migrations.AlterModelOptions(
            name='equestions3',
            options={'verbose_name': 'C. PRE CAPITAL (Equestions3)', 'verbose_name_plural': 'C. PRE CAPITAL (Equestions3)'},
        ),
        migrations.AlterModelOptions(
            name='equestions4',
            options={'verbose_name': 'D. Pre Market (Equestions4)', 'verbose_name_plural': 'D. Pre Market (Equestions4)'},
        ),
        migrations.AlterModelOptions(
            name='equestions5',
            options={'verbose_name': 'E. Ammount of Planned Raise (Equestions5)', 'verbose_name_plural': 'E. Ammount of Planned Raise (Equestions5)'},
        ),
        migrations.AlterModelOptions(
            name='equestions6',
            options={'verbose_name': 'F. Rounds of Capital (Equestions6)', 'verbose_name_plural': 'F. Rounds of Capital (Equestions6)'},
        ),
        migrations.AlterModelOptions(
            name='equestions7',
            options={'verbose_name': 'G. Use of Funds (Equestions7)', 'verbose_name_plural': 'G. Use of Funds (Equestions7)'},
        ),
        migrations.AlterModelOptions(
            name='equestions8',
            options={'verbose_name': 'H. RISK ASSESMENT (Equestions8)', 'verbose_name_plural': 'H. RISK ASSESMENT (Equestions8)'},
        ),
        migrations.AlterModelOptions(
            name='pre_rating',
            options={'verbose_name': 'K. Pre Rating', 'verbose_name_plural': 'K. Pre Ratings'},
        ),
        migrations.AlterModelOptions(
            name='referal_response',
            options={'verbose_name': 'L. Referal', 'verbose_name_plural': 'L. Referals'},
        ),
    ]
