# Generated by Django 5.1 on 2025-11-10 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise_questions', '0008_alter_documentsprepared_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='lending_requirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collateral_status', models.CharField(blank=True, choices=[('N/A', 'N/A'), ('Yes', 'Yes'), ('No', 'No'), ('Unknown', 'Unknown')], help_text='Select your collateral availability option.', max_length=255)),
                ('credit_score', models.IntegerField(blank=True)),
                ('criminal_history', models.CharField(blank=True, choices=[('None', 'None'), ('Misdemeanor', 'Misdemeanor'), ('Felony', 'Felony'), ('Fraud', 'Fraud'), ('Securities Violation', 'Securities Violation')], help_text='Point out any one of the criminal History from the options if any.', max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='referal_response',
            name='referral_source',
            field=models.CharField(choices=[('A Friend / Colleague', 'A Friend / Colleague'), ('Financial Advisor / Consultant', 'Financial Advisor / Consultant'), ('Social Media', 'Social Media'), ('Online Search', 'Online Search'), ('News / Article / Blog', 'News / Article / Blog'), ('Event / Webinar', 'Event / Webinar'), ('Other', 'Other')], default=None, max_length=255, null=True, verbose_name='How did you hear about us?'),
        ),
    ]
