# Generated by Django 5.1 on 2025-11-11 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise_questions', '0010_lending_requirements_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lending_requirements',
            name='collateral_status',
            field=models.CharField(blank=True, choices=[('Not Applicable', 'Not Applicable'), ('Yes', 'Yes'), ('No', 'No'), ('Unknown', 'Unknown')], help_text='Select your collateral availability option.', max_length=255),
        ),
        migrations.AlterField(
            model_name='lending_requirements',
            name='criminal_history',
            field=models.CharField(choices=[('None', 'None'), ('Misdemeanor', 'Misdemeanor'), ('Felony', 'Felony'), ('Fraud', 'Fraud'), ('Securities Violation', 'Securities Violation')], help_text='Point out any one of the criminal History from the options if any.', max_length=255),
        ),
    ]
