# Generated by Django 5.1 on 2025-11-11 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise_questions', '0011_alter_lending_requirements_collateral_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lending_requirements',
            name='criminal_history',
            field=models.JSONField(blank=True, default=list, help_text='Point out any one of the criminal History from the options if any.'),
        ),
    ]
