# Generated by Django 5.1 on 2025-11-11 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise_questions', '0012_alter_lending_requirements_criminal_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lending_requirements',
            name='criminal_history',
            field=models.JSONField(blank=True, choices=[('None', 'None'), ('Misdemeanor', 'Misdemeanor'), ('Felony', 'Felony'), ('Fraud', 'Fraud'), ('Securities Violation', 'Securities Violation')], default=list, help_text='Point out any one of the criminal History from the options if any.'),
        ),
    ]
