# Generated by Django 5.1 on 2025-11-11 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise_questions', '0015_alter_lending_requirements_criminal_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lending_requirements',
            name='credit_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
