# Generated by Django 5.1 on 2025-11-20 18:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise_questions', '0016_alter_lending_requirements_credit_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lending_requirements',
            name='credit_score',
            field=models.CharField(blank=True, choices=[('<580', '<580'), ('>620', '>620'), ('>680', '>680'), ('>720', '>720'), ('>760', '>760')], default=django.utils.timezone.now, help_text='Select your credit score option.', max_length=255),
            preserve_default=False,
        ),
    ]
