# Generated by Django 5.1 on 2025-12-17 15:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise_questions', '0017_alter_lending_requirements_credit_score'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='lending_requirements',
            new_name='LendingRequirements',
        ),
        migrations.RenameModel(
            old_name='pre_rating',
            new_name='PreRating',
        ),
        migrations.RenameModel(
            old_name='referal_response',
            new_name='ReferalResponse',
        ),
    ]
