from django import forms
from django.core.validators import MinValueValidator,MaxValueValidator
from django.utils.safestring import mark_safe

class ScoreForm(forms.Form):
    #C_TYPES =[
    #    ('Accelerator', 'Accelerator'),
    #    ('Bonds','Bonds'),
    #    ('Bootstrapped','Bootstrapped'),
    #    ('Commercial Banking','Commercial Banking'),
    #    ('Cryptocurrency','Cryptocurrency'),
    #    ('Factoring','Factoring'),
    #    ('Grants','Grants'),
    #    ('Hedge Funds','Hedge Funds'),
    #    ('Incubator','Incubator'),
    #    ('Investment Banking','Investment Banking'),
    #    ('Private Debt','Private Debt'),
    #    ('Private Equity Securities','Private Equity Securities'),
    #    ('Royalty Financing','Royalty Financing'),
    #    ('Small Business Administration (SBA)','Small Business Administration (SBA)'),
    #    ('Third Party Corporate Credit','Third Party Corporate Credit'),
    #    ('Tokenization','Tokenization'),
    #    ('Venture Capital','Venture Capital'),
    #]  
#
    C_TYPES = [
        ("Owner Debt - Cash Savings", "Owner Debt - Cash Savings"),
        ("Accelerator University", "Accelerator University"),
        ("Incubator - University", "Incubator - University"),
        ("Accelerator - Public", "Accelerator - Public"),
        ("Incubator - Public", "Incubator - Public"),
        ("Small Business Administration (SBA) - SBA Veteran", "Small Business Administration (SBA) - SBA Veteran"),
        ("Royalty Financing - Top Line Revenue", "Royalty Financing - Top Line Revenue"),
        ("Grants - Municipalities", "Grants - Municipalities"),
        ("Owner Debt - Whole Life Insurance", "Owner Debt - Whole Life Insurance"),
        ("Private Equity Securities - SAFE  Simple Agreement Future Equity", "Private Equity Securities - SAFE  Simple Agreement Future Equity"),
        ("Grants - Government", "Grants - Government"),
        ("Owner Debt - Home Equity", "Owner Debt - Home Equity"),
        ("Small Business Administration (SBA) - SBA Express", "Small Business Administration (SBA) - SBA Express"),
        ("Accelerator - Private", "Accelerator - Private"),
        ("Commercial Banking - Equipment Loan", "Commercial Banking - Equipment Loan"),
        ("Commercial Banking - Standby Letter of Credit (SBLC)", "Commercial Banking - Standby Letter of Credit (SBLC)"),
        ("Grants - Education Grants", "Grants - Education Grants"),
        ("Grants - State Agencies", "Grants - State Agencies"),
        ("Incubator - Private", "Incubator - Private"),
        ("Small Business Administration (SBA) - SBIC", "Small Business Administration (SBA) - SBIC"),
        ("Commercial Banking - Line of Credit", "Commercial Banking - Line of Credit"),
        ("Commercial Banking - Real Estate Loan", "Commercial Banking - Real Estate Loan"),
        ("Government Incentives Opportunity Zone Tax Credit Fund", "Government Incentives Opportunity Zone Tax Credit Fund"),
        ("Owner Debt - Retirement (401K) SDI", "Owner Debt - Retirement (401K) SDI"),
        ("Private Equity Securities - Family and Friends", "Private Equity Securities - Family and Friends"),
        ("Small Business Administration (SBA) - SBA 504B", "Small Business Administration (SBA) - SBA 504B"),
        ("Small Business Administration (SBA) - SBA 7A", "Small Business Administration (SBA) - SBA 7A"),
        ("Commercial Banking - Commercial Bank Loan", "Commercial Banking - Commercial Bank Loan"),
        ("Government Incentives - Enterprise Zones", "Government Incentives - Enterprise Zones"),
        ("Commercial Banking - Acquisition Loan", "Commercial Banking - Acquisition Loan"),
        ("Grants - Research Grants", "Grants - Research Grants"),
        ("Owner Debt - Personal Credit Cards", "Owner Debt - Personal Credit Cards"),
        ("Small Business Administration (SBA) - CDC/SBDC", "Small Business Administration (SBA) - CDC/SBDC"),
        ("Commercial Banking - Asset Based Lending", "Commercial Banking - Asset Based Lending"),
        ("Owner Debt - Personal Resources or Loans", "Owner Debt - Personal Resources or Loans"),
        ("Private Debt - Promissory Note", "Private Debt - Promissory Note"),
        ("Commercial Banking - Collateralized Debt", "Commercial Banking - Collateralized Debt"),
        ("Private Debt - Real Estate Loan", "Private Debt - Real Estate Loan"),
        ("Private Equity Securities - Family Offices", "Private Equity Securities - Family Offices"),
        ("Private Debt - Asset Based Lending", "Private Debt - Asset Based Lending"),
        ("Private Debt - Bridge Financing", "Private Debt - Bridge Financing"),
        ("Private Debt - Private Debt", "Private Debt - Private Debt"),
        ("Alternative - Apps (i.e. Cabbage)", "Alternative - Apps (i.e. Cabbage)"),
        ("Commercial Banking - Credit Card", "Commercial Banking - Credit Card"),
        ("Digital Currency - Investment via Crypto Wallet", "Digital Currency - Investment via Crypto Wallet"),
        ("Private Equity Securities - Angel Investors", "Private Equity Securities - Angel Investors"),
        ("Private Equity Securities - Convertible Note", "Private Equity Securities - Convertible Note"),
        ("Grants - Corporate Grants", "Grants - Corporate Grants"),
        ("Private Debt - Acquisition Loan", "Private Debt - Acquisition Loan"),
        ("Private Debt - Hard Money Loan", "Private Debt - Hard Money Loan"),
        ("Alternative - Corporate Credit (Third Party)", "Alternative - Corporate Credit (Third Party)"),
        ("Factoring - Accounts Receivable Loans", "Factoring - Accounts Receivable Loans"),
        ("Factoring - Merchant Account Advances", "Factoring - Merchant Account Advances"),
        ("Bonds - Government Backed", "Bonds - Government Backed"),
        ("Bonds - High Yield Junk", "Bonds - High Yield Junk"),
        ("Bonds - Mortgage Backed", "Bonds - Mortgage Backed"),
        ("Factoring - Purchase Order Loan", "Factoring - Purchase Order Loan"),
        ("Private Debt - Collateralized Debt", "Private Debt - Collateralized Debt"),
        ("Factoring - Invoice Factoring", "Factoring - Invoice Factoring"),
        ("Government Incentives - Gold Star", "Government Incentives - Gold Star"),
        ("Hedge Funds - Public", "Hedge Funds - Public"),
        ("Investment Banking - Mezzanine Financing", "Investment Banking - Mezzanine Financing"),
        ("Private Equity Securities - Regulation D 506(b)", "Private Equity Securities - Regulation D 506(b)"),
        ("Digital Currency - Stable Coins (DAO) - Blockchain", "Digital Currency - Stable Coins (DAO) - Blockchain"),
        ("Bonds - Foreign", "Bonds - Foreign"),
        ("Private Equity Securities - Regulation D 506(c)", "Private Equity Securities - Regulation D 506(c)"),
        ("Private Equity Securities - Rule 144", "Private Equity Securities - Rule 144"),
        ("Alternative - High Yield Business Consumer Loan", "Alternative - High Yield Business Consumer Loan"),
        ("Investment Banking - Investment Banker Debt", "Investment Banking - Investment Banker Debt"),
        ("Private Equity Securities - Regulation D 505", "Private Equity Securities - Regulation D 505"),
        ("Private Equity Securities - Sophisticated Individuals", "Private Equity Securities - Sophisticated Individuals"),
        ("Bonds - Investment Grade", "Bonds - Investment Grade"),
        ("Hedge Funds - Private", "Hedge Funds - Private"),
        ("Private Equity Securities - Regulation D 504", "Private Equity Securities - Regulation D 504"),
        ("Digital Currency - Cryptocurrency", "Digital Currency - Cryptocurrency"),
        ("Government Incentives - EB5 Immigration", "Government Incentives - EB5 Immigration"),
        ("Investment Banking - Broker Syndication", "Investment Banking - Broker Syndication"),
        ("Private Equity Securities - Accredited Investors", "Private Equity Securities - Accredited Investors"),
        ("Venture Capital - Short-Term Bridge Financing", "Venture Capital - Short-Term Bridge Financing"),
        ("Digital Currency - Tokenization", "Digital Currency - Tokenization"),
        ("Private Equity Securities - Private Placement Memorandum", "Private Equity Securities - Private Placement Memorandum"),
        ("Private Equity Securities - Regulation A", "Private Equity Securities - Regulation A"),
        ("Private Equity Securities - Regulation A Plus", "Private Equity Securities - Regulation A Plus"),
        ("Private Equity Securities - Regulation CF Tittle III", "Private Equity Securities - Regulation CF Tittle III"),
        ("Digital Currency - Initial Coin Offering", "Digital Currency - Initial Coin Offering"),
        ("Digital Currency - Initial Exchange Offering", "Digital Currency - Initial Exchange Offering"),
        ("Investment Banking - Broker Dealer Representation", "Investment Banking - Broker Dealer Representation"),
        ("Investment Banking - Equity Sale", "Investment Banking - Equity Sale"),
        ("Private Equity Securities - Broker Dealers", "Private Equity Securities - Broker Dealers"),
        ("Public Securities - Derivatives", "Public Securities - Derivatives"),
        ("Public Securities - SPAC - Special Purpose Acquisition Company", "Public Securities - SPAC - Special Purpose Acquisition Company"),
        ("Venture Capital - Mezzanine Financing", "Venture Capital - Mezzanine Financing"),
        ("Public Securities - Market Maker", "Public Securities - Market Maker"),
        ("Public Securities - Money Market Instruments", "Public Securities - Money Market Instruments"),
        ("Public Securities - PIPE Private Investment in Public Entity", "Public Securities - PIPE Private Investment in Public Entity"),
        ("Venture Capital - Long Term Debt", "Venture Capital - Long Term Debt"),
        ("Public Securities - Initial Public Offering (IPO)", "Public Securities - Initial Public Offering (IPO)"),
        ("Public Securities - OTC Over the Counter", "Public Securities - OTC Over the Counter"),
        ("Venture Capital - Mergers and Acquisitions Financing", "Venture Capital - Mergers and Acquisitions Financing"),
        ("Venture Capital - Equity Sale", "Venture Capital - Equity Sale"),
    ]


    cname = forms.ChoiceField(choices = C_TYPES,label = 'Choose the Capital Type to create the algorithm for:' )

    def __init__(self, *args, **kwargs):
        # Extract 'categories' from kwargs
        categories = kwargs.pop('categories', [])
        super().__init__(*args, **kwargs)
        
        # Dynamically add fields for each category
        for category in categories:
            self.fields[f'score_{category}'] = forms.ChoiceField(
                choices=[(i, str(i)) for i in range(11)],
                widget=forms.RadioSelect(attrs={'class': 'vertical-radio'}),
                label=category,
            )
            self.fields[f'additional_score_{category}'] = forms.ChoiceField(
                choices=[(0, '0'), (1, '1')],
                widget=forms.Select,
                label=f"Additional Score ({category})",
            )

