# Generated by Django 5.1 on 2026-05-18 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Stable identifier referenced by the frontend (e.g. "monthly").', max_length=64, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('stripe_product_id', models.CharField(blank=True, default='', max_length=120)),
                ('stripe_price_id', models.CharField(blank=True, default='', max_length=120)),
                ('amount_cents', models.PositiveIntegerField(help_text='Price in the smallest currency unit (e.g. cents for USD).')),
                ('currency', models.CharField(default='usd', max_length=3)),
                ('interval', models.CharField(choices=[('month', 'Monthly'), ('year', 'Yearly')], max_length=10)),
                ('supports_trial', models.BooleanField(default=False, help_text='If True, Checkout sessions for this plan can request a trial via `subscription_data.trial_period_days`.')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this plan is currently offered on the pricing page.')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Subscription plan',
                'verbose_name_plural': 'Subscription plans',
                'ordering': ['sort_order', 'amount_cents'],
            },
        ),
    ]
