# Generated by Django 5.1 on 2026-05-18 10:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
        ('tenants', '0004_client_current_period_end_client_stripe_customer_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingOnboarding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_session_id', models.CharField(max_length=255, unique=True)),
                ('stripe_customer_id', models.CharField(blank=True, default='', max_length=255)),
                ('stripe_subscription_id', models.CharField(blank=True, default='', max_length=255)),
                ('with_trial', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=254)),
                ('company_name', models.CharField(blank=True, default='', max_length=200)),
                ('onboarding_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('onboarded', 'Onboarded'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('onboarded_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tenants.client')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pending_onboardings', to='subscriptions.plan')),
            ],
            options={
                'verbose_name': 'Pending onboarding',
                'verbose_name_plural': 'Pending onboardings',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='subscriptio_status_2ebc8f_idx'), models.Index(fields=['stripe_customer_id'], name='subscriptio_stripe__f04f8c_idx')],
            },
        ),
    ]
