info = {
    '66- Private Equity Securities - Regulation CF Tittle III':"""<p>Crowdfunding (Title III of the JOBS Act) falls under securities laws allowing it to be used to offer general solicitation to sell securities.  Crowdfunding permits individuals to invest in securities-based crowdfunding transactions subject to certain investment limits. The rules also limit the amount of money an issuer can raise using the crowdfunding exemption, impose disclosure requirements on issuers for certain information about their business and securities offering, and create a regulatory framework for the broker-dealers and funding portals that facilitate the crowdfunding transactions.
    </p>
    <p>
    Regulation Crowdfunding permits a company to raise a maximum aggregate amount of up to $5,000,000 through crowdfunding offerings in a 12-month period. Additionally, the rules permit individual investors, over a 12-month period, to invest in the aggregate across all crowdfunding offerings up to:
    </p>
    <p>
    If either their annual income or net worth is less than $100,000, than the greater of:
    <p>•	$2,000 or</p>
    <p>•	Five percent of the lesser of their annual income or net worth.</p>
    If both their annual income and net worth are equal to or more than $100,000, 10% of the lesser of their annual income or net worth; and during the 12-month period, the aggregate amount of securities sold to an investor through all crowdfunding offerings may not exceed $100,000.
    </p>
    Entrepreneurs should begin preparing themselves if they intend to participate in Title III crowdfunding by attending education forums to learn the rules and regulations regarding solicitation, marketing, advertising, compliance, pre-investment documentation, proper disclosures, the use of compliant investment operating systems, investor data management, security, information management, and post-investment documentation.  
    <p>
    One of the key investor protections of Title III of the JOBS Act is the requirement that Regulation Crowdfunding transactions take place through an SEC-registered intermediary, either a broker-dealer or a funding portal. Under Regulation Crowdfunding, offerings must be conducted exclusively through a platform operated by a registered broker or a funding portal, which is a new type of SEC registrantion. <strong><p>The rules require these intermediaries to:</p></strong>
    <p>•	Provide investors with educational materials.</p>
    <p>•	Take measures to reduce the risk of fraud.</p>
    <p>•	Make issuer and offering information available.</p>
    <p>•	Provide communication channels to permit discussions about offerings on the platform; and</p>
    <p>•	Facilitate the offer and sale of crowdfunded securities.</p>
    </p>
    <strong>The rules prohibit funding portals from:</strong>
    <p>
    <p>•	Offering investment advice or recommendations.</p>
    <p>•	Soliciting purchases, sales or offers to buy securities offered or displayed on its platform.</p>
    <p>•	Compensating promoters and others for solicitations or based on the sale of securities; and</p>
    <p>•	Holding, possessing, or handling investor funds or securities.</p>
    </p>
    <p>
    The rules provide a safe harbor under which funding portals can engage in certain activities consistent with these restrictions.  An example of a Regulated Funding Portal is Fundify.com.</p>""",

    '65- Private Equity Securities - Regulation A':"""
    <p>"A newly revamped securities regulation that companies can rely on to raise up to $75,000,000 from accredited and non-accredited investors alike. In traditional funding (Regulation D, Rule 506 (b) / (c) offerings) companies are either limited to having up to 35 non-accredited investors in their round or completely banned from onboarding non-accredited investors altogether. Accredited investors make up less than one percent of the US population, meaning 99% of people previously couldn’t invest in startups even if they understood the risk and had the liquid capital to deploy. Regulation A has been around for years but has not been widely used mainly because of the way the rules were written, making raising capital quite inefficient. In fact, the Securities and Exchange Commission (SEC) estimated only 26 offerings were conducted annually and they were capped at an upper funding limit of $5,000,000. Whereas now, with Regulation A+, companies can raise up to $20,000,000 on Tier 1 and up to $75,000,000 on Tier 2, which changes the game."</p>

    <p> Raising Capital Using a Regulation A+ Mini-IPO (n.d.). Seed Invest. Retrieved from <a href = "https://www.seedinvest.com/blog/jobs-act/raising-capital-reg-a-mini-ipo">www.seedinvest.com/blog/jobs-act/raising-capital-reg-a-mini-ipo</a></p>""",

    '1- Private Equity':"""<p>Rule 506(c) of Regulation D (Title II of the JOBS Act)

    <p>Section 201(a) of the JOBS Act requires the SEC to eliminate the prohibition on using general solicitation under Rule 506 where all purchasers of the securities are accredited investors, and the issuer takes reasonable steps to verify that the purchasers are accredited investors. To implement Section 201(a), the SEC adopted paragraph (c) of Rule 506. Under Rule 506(c), issuers can offer securities through means of general solicitation, provided that:</p>
    <p>• all purchasers in the offering are accredited investors.</p>
    <p>• the issuer takes reasonable steps to verify their accredited investor status; and</p>
    <p>• certain other conditions in Regulation D are satisfied.</p>

    <p>Accredited Investors</p>
    <p>“Accredited investor” is a term used by the Securities and Exchange Commission (SEC) under Regulation D to refer to investors who are financially sophisticated and have a reduced need for the protection provided by certain government filings. In order for an individual to qualify as an accredited investor, he or she must accomplish at least one of the following: 1) earn an individual income of more than $200,000 per year, or a joint income of $300,000, in each of the last two years and expect to maintain the same level of income; 2) have a net worth exceeding $1,000,000, either individually or jointly with a spouse; and 3) be a general partner, executive officer, director or a related combination thereof for the issuer of a security being offered."</p>""",

    '77- Small Business Administration (SBA) - SBA 504B':"""<p>SBA 504B Real Estate/Other Loans + Future Roastery</p>
    <p>The CDC/504 loan program is a long-term financing tool, designed to encourage economic development within a community. The 504 program accomplishes this by providing small businesses with long-term, fixed-rate financing to acquire major fixed assets for expansion or modernization. A Certified Development Company (CDC) is a private, nonprofit corporation which is set up to contribute to economic development within its community. CDCs work with SBA and private sector lenders to provide financing to small businesses, which accomplishes the goal of community economic development. Typically, a CDC/504 project includes: 1) a loan secured from a private sector lender with a senior lien covering up to 50% of the project cost; 2) a loan secured from a CDC (backed by a 100% SBA-guaranteed debenture) with a junior lien covering up to 40% of the project cost; 3) a contribution from the borrower of at least 10% of the project cost (equity); and 4) this type of setup means that 100% of the project cost is covered either by contribution of equity by the borrower, or the senior or junior lien. Proceeds from 504 loans must be used for fixed asset projects, such as: 1) the purchase of land, including existing buildings; 2) the purchase of improvements, including grading, street improvements, utilities, parking lots and landscaping; 3) the construction of new facilities or modernizing, renovating or converting existing facilities; and 4) The purchase of long-term machinery and equipment.</p>
    <p>To be eligible for a CDC/504 loan, the business must be operated for profit and fall within the size standards set by the SBA. Under the 504 Program, a business qualifies as small if it does not have a tangible net worth in excess of $7,500,000 and does not have an average net income in excess of $2,500,000 after taxes for the preceding two years. Loans cannot be made to businesses engaged in speculation or investment in rental real estate. The maximum SBA debenture is $1,500,000 when meeting the job creation criteria or a community development goal. Generally, the business must create or retain one job for every $65,000 provided by the SBA, except for small manufacturers which have a $100,000 job creation or retention goal.</p>""",

    '21- Commercial Banking - Line of Credit':"""<p>Instead of getting a check for the full amount of the loan, the financial institution allows a company to borrow up to a certain amount per year – it takes out the money in increments as needed. The flexibility comes at a cost, though: if the loan balance is not repaid fairly quickly, lines of credit can quickly become more expensive than other types of loans. A line of credit should be avoided for significant business improvements. They are designed for temporary cash shortfalls.</p>"
									
    <p>There are three basic types of lines of credit including ‘committed,’ ‘revocable’ and ‘stand-by.’ Committed credit lines are a monetary spending loan balance offered by a financial institution that cannot be suspended without notifying the borrower. A committed credit line is a legal agreement between the financial institution and the borrower outlining the conditions of the credit line. Once signed, the agreement requires the financial institution to lend money to the borrower, provided that the borrower does not break the conditions. Lenders may require the borrower to pay a fee based on the amount that can be borrowed. Committed credit lines differ from uncommitted credit lines in that they legally bind the lender to provide the funds, rather than giving the lender the option of suspending or canceling the credit line based on market conditions."</p>""",

    'Regulation D 506B' : """<p>Section 201(a) of the JOBS Act requires the SEC to eliminate the prohibition on using general solicitation under Rule 506 where all purchasers of the securities are accredited investors, and the issuer takes reasonable steps to verify that the purchasers are accredited investors. To implement Section 201(a), the SEC adopted paragraph (c) of Rule 506. Under Rule 506(c), issuers can offer securities through means of general solicitation, provided that:</p>
    <p>• all purchasers in the offering are accredited investors.</p>
    <p>• the issuer takes reasonable steps to verify their accredited investor status; and</p>
    <p>• certain other conditions in Regulation D are satisfied."</p>
    <p>Trebour, C. (2015, July 17). Top 5 advantages of Rule 506(c). WealthForge. Retrieved from <a href= "https://www.wealthforge.com/insights/top-5-advantages-of-rule-506c/">www.wealthforge.com/insights/top-5-advantages-of-rule-506c/</a></p>

    <p>Private Placement Memorandum (PPM)</p>
    <p>In preparing for a private placement, the company prepares offering materials containing information about the company and the securities being offered. A private placement memorandum (PPM) is most often created with multiple sections including the offering, risks and disclosures, a business description or business plan, subscription agreements and company operating agreements. In order to sell unregistered securities, the company must produce a PPM which describes the company’s intentions (use of funds) and declare its status as an unregistered security. A PPM typically includes: 1) Executive Summary; 2) the offering (terms of the offering); 3) risks and disclosures; (4) business description (business plan); 5) Operating Agreement; and 6) Subscription Agreement."</p>
    <p>[31] Aponte, A. (n.d.). What is a private placement memorandum? NOLO. Retrieved from <a href = "https://www.nolo.com/legal-encyclopedia/what-is-private-placement-memorandum.html">www.nolo.com/legal-encyclopedia/what-is-private-placement-memorandum.html"</a></p>
							
    <p>Accredited & Non Accredited Investors</p>
    <p>“Accredited investor” is a term used by the Securities and Exchange Commission (SEC) under Regulation D to refer to investors who are financially sophisticated and have a reduced need for the protection provided by certain government filings. In order for an individual to qualify as an accredited investor, he or she must accomplish at least one of the following: 1) earn an individual income of more than $200,000 per year, or a joint income of $300,000, in each of the last two years and expect to maintain the same level of income; 2) have a net worth exceeding $1,000,000, either individually or jointly with a spouse; and 3) be a general partner, executive officer, director or a related combination thereof for the issuer of a security being offered."</p>

    <p>Rule 506(b) of Regulation D enables Issuers to issue an unlimited amount of Securities so long as no more than 35 non-accredited Investors participate in the Offering.</p>
    <p>Investors participating in a Rule 506(b) Private Placement must complete an “Accredited Investor Questionnaire” (see “Accredited Investor Questionnaire”).</p>
    <p>What Is Required To Become An Accredited Investor in a Private Placement? Retrieved from <a href = "https://www.investopedia.com/ask/answers/042115/what-required-become-accredited-investor-private-placement.asp">www.investopedia.com/ask/answers/042115/what-required-become-accredited-investor-private-placement.asp</a></p>""",

    'Exempt Securities': """ <p>"An exempt transaction is a type of securities transaction where a business does not need to file registrations with any regulatory bodies, provided the number of securities involved is relatively minor compared to the scope of the issuer's operations and that no new securities are being issued. Exempt securities are the instruments used that the government backs, which have tax-exempt status. An exempt transaction is a securities exchange that would otherwise have to register with the Securities and Exchange Commission (SEC) but does not because of the nature of the transaction in question."</p>												
    <p><a href="https://www.investopedia.com/terms/e/exempttransaction.asp">www.investopedia.com/terms/e/exempttransaction.asp</a></p>""",

    '75- Private Equity Securities - Simple Agreement Future Equity':"""<p>A Simple Agreement for Future Equity (SAFE) is a financing contract that may be used by a startup company to raise capital in its seed financing rounds. A SAFE is an investment contract between a startup and an investor that gives the investor the right to receive equity of the company on certain triggering events, such as a: 1) future equity financing (known as a next equity financing or qualified financing), usually led by an institutional venture capital (VC) fund; and 2) Sale of the company: the price of the equity that the SAFE holders receive on conversion is lower than the price of the securities issued to VC investors in connection with a next equity financing, based on either a discount rate or valuation cap. A SAFE is viewed by some as a more founder-friendly alternative to convertible notes.  • all purchasers in the offering are accredited investors.</p>
    <p>• the issuer takes reasonable steps to verify their accredited investor status; and</p>
    <p>• certain other conditions in Regulation D are satisfied."</p>
    <p>SAFEs have all the same conversion features as convertible notes but lack the debt hallmarks. In particular, a SAFE has no: maturity date, until a conversion event occurs; SAFEs remain outstanding indefinitely. Accruing interest- investors receive only a right to convert their SAFEs into equity at a lower price than the investors in the subsequent financing (based either on the discount or valuation cap in their SAFEs).</p> 
    <p>SAFEs are a relatively recent addition (2013) to the seed financing, security crowdfunding toolkit, popularized by the premier startup accelerator, Y Combinator.  Other players in the startup finance ecosystem have created form documents similar to the SAFE but using different names. These include: the convertible security proposed by a partner at the law firm of Wilson Sonsini Goodrich & Rosati and the Keep it Simple Security (KISS) created by 500 Startups, another startup accelerator.”</p> """,

    'Business Accelerator':"""<p>“A business accelerator is a program that gives developing companies access to mentorship, investors, and other support that can help them become stable and self-sufficient. Companies that use business accelerators are generally startups that have moved beyond the earliest stages of getting established. They have entered into ‘adolescence’, meaning that they can stand on their own two feet but need guidance and peer support to gain strength. An accelerator program can last anywhere for two to six months. The goal is for the company to emerge ready to stand on their own, with strong positioning to claim a share of their target markets.”</p> 				
    <p><a href = "https://www.bdc.ca/en/articles-tools/entrepreneur-toolkit/templates-business-guides/glossary/business-accelerator">www.bdc.ca/en/articles-tools/entrepreneur-toolkit/templates-business-guides/glossary/business-accelerator</a></p>""",

    'Business Incubator':"This will be replaced by the brief definition of the capital types once the defination is finalized (DUMMY TEXT FOR NOW)",

    '79- Small Business Administration (SBA) - SBA Micro Lender':"""The SBA Microlender Program provides small businesses with up to $50,000 to drive economic growth and foster innovation. The program is designed particularly for those from underserved communities. In an effort to address this issue, the Small Business Administration (SBA) has partnered with microlenders, including Community Development Financial Institutions (CDFIs), to provide crucial financing options.
    
    SBA microlenders are nonprofit organizations or mission-driven financial institutions that offer small loans, often referred to as microloans, to entrepreneurs who may not qualify for traditional bank loans. These lenders collaborate with the SBA to provide affordable financing options to aspiring business owners, particularly those from low-income backgrounds or underserved communities.
    
    SBA microloans typically range from a few thousand dollars up to $50,000, making them ideal for small businesses with modest capital needs. This flexibility allows entrepreneurs to obtain the necessary funds to start or expand their ventures, purchase equipment, or cover working capital requirements.
    
    SBA microlenders often have more lenient eligibility requirements compared to traditional lenders. They consider factors beyond credit scores, such as character, experience, and the viability of the business idea. This opens up opportunities for entrepreneurs who might not meet conventional lending criteria.""",    
}