# Generated by Django 5.1 on 2026-04-29 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='allCapitalMatchValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.JSONField(default=dict)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Capital_Matches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RCF_1', models.FloatField(default=0, verbose_name='Regulation Crowdfunding')),
                ('RAP_2', models.FloatField(default=0, verbose_name='Regulation A+')),
                ('PE_3', models.FloatField(default=0, verbose_name='Private Equity')),
                ('SBA_504B_4', models.FloatField(default=0, verbose_name='SBA 504(b) Loan')),
                ('LOCACD_5', models.FloatField(default=0, verbose_name='Line of Credit - Accounts Receivable')),
                ('RD_506B_6', models.FloatField(default=0, verbose_name='Regulation D 506(b)')),
                ('ES_7', models.FloatField(default=0, verbose_name='Equity Shares')),
                ('S_SAFE_8', models.FloatField(default=0, verbose_name='Simple Agreement for Future Equity (SAFE)')),
                ('BA_9', models.FloatField(default=0, verbose_name='Bank Financing')),
                ('BI_10', models.FloatField(default=0, verbose_name='Bond Issuance')),
                ('SBAML_11', models.FloatField(default=0, verbose_name='Small Business Administration Microloan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Capital Match Percentages',
                'verbose_name_plural': 'Capital Match Percentages',
            },
        ),
        migrations.CreateModel(
            name='Letter_Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='', max_length=255)),
                ('lastname', models.CharField(default='', max_length=255)),
                ('address', models.CharField(default='', max_length=255)),
                ('phone', models.CharField(default='', max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('businessname', models.CharField(default='', max_length=255)),
                ('count', models.CharField(default='', max_length=255)),
                ('fundgoal', models.CharField(default='', max_length=255)),
                ('totalnum', models.IntegerField(default=0)),
                ('cm1name', models.CharField(default='', max_length=255)),
                ('cm2name', models.CharField(default='', max_length=255)),
                ('cm3name', models.CharField(default='', max_length=255)),
                ('cm4name', models.CharField(default='', max_length=255)),
                ('cm5name', models.CharField(default='', max_length=255)),
                ('cm6name', models.CharField(default='', max_length=255)),
                ('cm1no', models.IntegerField(default=0)),
                ('cm2no', models.IntegerField(default=0)),
                ('cm3no', models.IntegerField(default=0)),
                ('cm4no', models.IntegerField(default=0)),
                ('cm5no', models.IntegerField(default=0)),
                ('cm6no', models.IntegerField(default=0)),
                ('intermediaries', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('totalprice', models.IntegerField(default=0)),
                ('discount', models.IntegerField(default=0)),
                ('balancedue', models.IntegerField(default=0)),
                ('top_6_name', models.JSONField()),
                ('top_6_name_output', models.JSONField()),
                ('infocm1', models.TextField(default='', max_length=100000)),
                ('infocm2', models.TextField(default='', max_length=100000)),
                ('infocm3', models.TextField(default='', max_length=100000)),
                ('infocm4', models.TextField(default='', max_length=100000)),
                ('infocm5', models.TextField(default='', max_length=100000)),
                ('infocm6', models.TextField(default='', max_length=100000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'JSON output for fields required in letter',
                'verbose_name_plural': 'JSON output for fields required in letter',
            },
        ),
        migrations.CreateModel(
            name='Matches_Purchased',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_matches', models.TextField(max_length=3000)),
                ('total_num', models.IntegerField(default=0)),
                ('price', models.FloatField(default=0)),
                ('total_price', models.FloatField(default=0)),
                ('balance_due', models.FloatField(default=0)),
                ('discount', models.FloatField(default=0)),
                ('match_id_cm', models.JSONField(default=list)),
                ('match_id_i', models.JSONField(default=list)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Purchased number of matches',
                'verbose_name_plural': 'Purchased number of matches',
            },
        ),
        migrations.CreateModel(
            name='Purchases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cm1purchase', models.IntegerField(default=0)),
                ('cm2purchase', models.IntegerField(default=0)),
                ('cm3purchase', models.IntegerField(default=0)),
                ('cm4purchase', models.IntegerField(default=0)),
                ('cm5purchase', models.IntegerField(default=0)),
                ('cm6purchase', models.IntegerField(default=0)),
                ('ipurchase', models.IntegerField(default=0)),
                ('cm_matches', models.JSONField(default=list)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Purchased number of matches',
                'verbose_name_plural': 'Purchased number of matches',
            },
        ),
    ]
